# Update <REGISTRY> <NAMESPACE> values before use
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nwan-fire-server
  labels:
    app: nwan-fire-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nwan-fire-server
  template:
    metadata:
      labels:
        app: nwan-fire-server
    spec:
      containers:
      - name: nwan-fire-server
        image: <REGISTRY>/<NAMESPACE>/myapp:v1.1.0
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        env:
        - name: CLOUDANT_URL
          valueFrom:
            secretKeyRef:
              name: cloudant
              key: url
              optional: true
        - name: CLOUDANT_IAM_API_KEY
          valueFrom:
            secretKeyRef:
              name: cloudant
              key: iamApiKey
              optional: true

